%YAML:1.0
#feature traker paprameters
max_cnt: 150                # max feature number in feature tracking
min_dist: 30                # min distance between two features
affine: 0                   # affine tracking
weighted: 0                 # weighted tracking
max_level: 3                # max pyramid level

flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy
D_threshold: 0.5        # flow back threshold (pixel)

show_feature: 1           # show tracked features in the images
